classdef enumExplainerModels
	properties (Constant)
        predictorImportance = (["ClassificationTree", ...
                                "classreg.learning.classif.CompactClassificationTree", ...
                                "classreg.learning.classif.ClassificationEnsemble", ...
                                "classreg.learning.classif.CompactClassificationEnsemble", ...
                                "RegressionTree", ...
                                "classreg.learning.regr.CompactRegressionTree", ...
                                "classreg.learning.regr.RegressionEnsemble", ...
                                "classreg.learning.regr.CompactRegressionEnsemble"])
        
        OOB                 = (["classreg.learning.classif.ClassificationEnsemble", ...
                                "classreg.learning.regr.RegressionEnsemble"])
        OOBMethods          = "Bag"
   end
end