classdef enumExplainerModels
	properties (Constant)
        
        classif             = "classreg.learning.classif"
        regr                = "classreg.learning.regr"
        
        
        regression          = (["CompactGeneralizedLinearModel", ...  
                                "GeneralizedLinearMixedModel", ...
                                "LinearModel", ...
                                "CompactLinearModel", ...
                                "LinearMixedModel", ...
                                "NonLinearModel", ...
                                "RegressionEnsemble", "RegressionBaggedEnsemble", "CompactRegressionEnsemble", ...
                                "RegressionGAM", "CompactRegressionGAM", ...
                                "CompactRegressionGP", ...
                                "RegressionKernel", ...
                                "RegressionLinear", ...
                                "RegressionNeuralNetwork", "CompactRegressionNeuralNetwork", ...
                                "RegressionSVM", "CompactRegressionSVM", ...
                                "RegressionTree", "CompactRegressionTree", ...
                                "TreeBagger", "CompactTreeBagger"])
        
        classification      = (["ClassificationDiscriminant", "CompactClassificationDiscriminant", ...
                                "ClassificationECOC", "CompactClassificationECOC", ...
                                "ClassificationEnsemble", "CompactClassificationEnsemble", "ClassificationBaggedEnsemble", ...
                                "ClassificationGAM", "CompactClassificationGAM", ...
                                "ClassificationKernel", ...
                                "ClassificationKNN", ...
                                "ClassificationLinear", ...
                                "ClassificationNaiveBayes", "CompactClassificationNaiveBayes", ...
                                "ClassificationNeuralNetwork", "CompactClassificationNeuralNetwork", ...
                                "ClassificationSVM", "CompactClassificationSVM", ...
                                "ClassificationTree", "CompactClassificationTree", ...
                                "TreeBagger", "CompactTreeBagger"])
        
        predictorImportance = (["ClassificationTree", ...
                                "classreg.learning.classif.CompactClassificationTree", ...
                                "classreg.learning.classif.ClassificationEnsemble", ...
                                "classreg.learning.classif.CompactClassificationEnsemble", ...
                                "RegressionTree", ...
                                "classreg.learning.regr.CompactRegressionTree", ...
                                "classreg.learning.regr.RegressionEnsemble", ...
                                "classreg.learning.regr.CompactRegressionEnsemble"])
        
        OOB                 = (["classreg.learning.classif.ClassificationEnsemble", ...
                                "classreg.learning.regr.RegressionEnsemble"])
        OOBMethods          = "Bag"
        
   end
end

